name: Artifact
on: push
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: date > date.txt
      - uses: actions/upload-artifact@v4
        with:
          name: uploaded
          path: date.txt
          retention-days: 1
  download:
    runs-on: ubuntu-latest
    needs: [upload]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: uploaded
          path: download
      - run: ls -ltra
      - run: cat download/date.txt
